name: Auto Click

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # 每2小时运行一次

jobs:
  click:
    runs-on: ubuntu-latest
    container: selenium/standalone-chrome:latest  # 用官方带Chrome的容器

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Run auto click
      run: python auto_click.py
